# Generated by Django 2.0.4 on 2020-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zanr',
            name='kniha',
        ),
        migrations.AddField(
            model_name='kniha',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knihy.Zanr'),
        ),
    ]
